remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: gmzii.things
logo: /assets/img/logo.png
description: tentatively a digital side of myself
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
